### ISSUE TITLE
Add a Debian package

### ISSUE THREAD

**Issue by vidy007** [SwayKh/linksym#1]
Hello, i've just created a deb package for linksym. It installs and works without any problem. Can you add it in releases? I'll be maintaining it

Can't upload that sort of files to github, so here is gdrive link: https://drive.google.com/file/d/18nleNcH006mmzQG57KOFfxSmbqLKoxwb/view?usp=sharing

**Comment by SwayKh** [comment]
Thanks for the Issue!

Since I use goreleaser to manage my releases, after digging through the documentation I found that it can create linux package for releases. So the newest release should now have .deb and .rpm packages.

Can you try out the releases to see if they work properly or not? Feel free to provide any more feedback you have.
